name: medicine_reminder
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^0.5.7
  table_calendar: ^2.2.3
  syncfusion_flutter_datepicker: ^18.3.44-beta
  lite_rolling_switch: ^0.1.1
  font_awesome_flutter: 8.10.0
  flutter_svg: ^0.19.1
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.0
  qr_flutter: ^3.2.0
  rive: ^0.6.2+2
  cloud_firestore: ^0.14.1+3
  uuid: ^2.2.2
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  permission_handler: ^5.0.1+1
  firebase_messaging: ^7.0.3
  google_fonts:
  intl:
  timeago:
  image:
  image_picker: ^0.6.7+12
  simple_animations: ^2.2.3
  flutter_icons:
  folding_cell:
  flare_flutter:
  rxdart:
  provider: ^4.3.2+2
  flutter_local_notifications: ^3.0.2
  qrscan: ^0.2.19
  flutter_neumorphic: ^3.0.3
  weekday_selector: ^0.4.0
  slide_countdown_clock: ^1.0.3
  curved_navigation_bar: ^0.3.4
  fab_circular_menu: ^1.0.0
  flutter_spinkit: ^3.1.0
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.9
  url_launcher: ^5.4.2
  http: ^0.12.2
  flutter_rating_bar: ^3.2.0+1
  image_cropper: 1.0.2
  google_sign_in: ^4.5.6
  flutter_typeahead: ^1.9.1
  flutter_vibrate: ^1.0.0
  flutter_barcode_scanner: ^1.0.1
  lottie: ^0.7.0+1
  neumorphic:
  flutter_native_timezone: ^1.0.4
  android_alarm_manager: ^0.4.5+17
  liquid_pull_to_refresh: ^2.0.0
  shared_preferences: ^0.5.12+4
  path_provider: ^1.2.0
  get_it:
  progress_hud: ^1.1.0
  firebase_ml_vision: ^0.9.10


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"

  flutter_test:
    sdk: flutter
flutter_icons:
    android: true
    ios: true
    image_path: "assets/Logo/AppLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - images/pill.png
     - images/logo_white.png
     - images/
     - images/applogononame.png
     - assets/Rive/
     - images/App_logo_plain.png
     - lang/en.json
     - lang/hi.json
     - lang/ml.json
     - data/liquid.json



  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
        - asset: assets/fonts/CircularAir-Light.ttf
          weight: 100
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 500
    - family: Ic
      fonts:
        - asset: assets/fonts/ic_medicine.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
